<?php

namespace Illuminate\Tests;

use PHPUnit\Framework\TestCase;

class Test extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testBasic()
    {
        $this->assertTrue("1 + 1", 2);
    }
}
